# Generated by Django 2.2.28 on 2024-11-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='etat_de_sante',
            field=models.CharField(default='Bonne santé', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_de_sécurite_sociale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salle',
            name='capacite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital.Salle')),
            ],
        ),
    ]
