# Generated by Django 2.2.28 on 2024-11-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_auto_20241123_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='soigne',
            field=models.BooleanField(default=False),
        ),
    ]
