# Generated by Django 2.2.28 on 2024-11-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0005_auto_20241124_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='etat_de_sante',
            field=models.CharField(choices=[('Bonne santé', 'Bonne santé'), ('Décédé', 'Décédé'), ('Hospitalisé', 'Hospitalisé'), ('En opération', 'En opération'), ('Repos', 'Repos'), ('En réanimation', 'En réanimation')], default='Bonne santé', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital.Salle'),
        ),
    ]
