# Generated by Django 2.2.28 on 2024-11-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0006_auto_20241124_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hopital.Salle'),
        ),
    ]
